/*
	Media.js
	--------

	This class handles the state for the Media toy system.

	NOTE: it does not handle the rendering, which will be the widgets.
*/

// vue
import { ref, shallowRef, watch } from 'vue';
import { socketRef, socketShallowRef, socketShallowRefAsync, bindRef } from 'socket-ref';

// our app
import Toy from "../Toy";
import { StateTickerQueue } from '@scripts/StateTickerQueue';

// components
import MediaPage from './MediaPage.vue';
import MediaWidget from './MediaWidget.vue';

// main export
export default class Media extends Toy {

	// static info
	static name = 'Media';
	static slug = 'media';
	static desc = 'Display images, GIFs, or play sounds on your stream.';
	static optionsPageComponent = MediaPage;
	static themeColor = '#51547D';
	static widgetComponents = [
		{
			component: MediaWidget,
			key: 'widgetBox',
			allowResize: true,
			lockAspectRatio: false,
			description: 'Shows a picture, gif, and plays a sound. Can be placed anywhere.',
			slug: 'mediaBox'
		}
	];


	/**
	 * Constructs the Media object
	 * 
	 * @param {ToyManager} toyManager - reference to the toy manager
	 */
	constructor(toyManager) {

		// call the parent constructor
		super(toyManager);

		// our state ticker queue
		this.stateTickerQueue = new StateTickerQueue(this.handleStateChange.bind(this), 2, 5);
		this.tickFN = () => this.stateTickerQueue.tick()
		electronAPI.tick(this.tickFN);

		// live socket settings
		this.mode = socketShallowRef(this.static.slugify('mode'), 'IDLE');
		this.author = socketShallowRef(this.static.slugify('author'), '');
		this.commandName = socketShallowRef(this.static.slugify('commandName'), '');
		this.message = socketShallowRef(this.static.slugify('message'), '');
		this.soundPath = socketShallowRef(this.static.slugify('soundPath'), null);
		this.imagePath = socketShallowRef(this.static.slugify('imagePath'), null);
		this.volume = socketShallowRef(this.static.slugify('volume'), 1);
		this.scale = socketShallowRef(this.static.slugify('scale'), 1);

		// keep our media assets in sync with the custom commands
		this.reconcileMediaAssets();
		watch(this.chatToysApp.commands, () => {
			this.reconcileMediaAssets();
		}, { deep: true });

	}


	/**
	 * Reconciles the media assets with the current list of custom commands for this toy.
	 */
	reconcileMediaAssets() {

		const commands = this.chatToysApp.commands.value;
		const mediaAssets = this.settings.mediaAssets.value;

		// get all keys of the commandsRef.value as an array
		const commandKeys = Object.keys(commands);
		const currentCommandsSlugs = commandKeys.filter(slug => slug.startsWith(this.slug));

		// keep list of new media assets to add to our settings state
		const newMediaAssets = [];

		// loop over our new command slugs & make new media assets objects if they don't exist
		currentCommandsSlugs.forEach((slug) => {

			// get the command object
			const command = commands[slug];

			// check if we already have a media asset for this command
			const existingAsset = mediaAssets.find(asset => asset.commandSlug === slug);
			if(!existingAsset){

				// create a new media asset object
				newMediaAssets.push({
					commandSlug: slug,
					commandName: command.command,
					hasImage: true,
					imageId: "6",
					hasSound: true,
					soundId: "13",
					duration: 10,
					volume: 1,
					scale: 1,
				});
			}
		});

		// now loop over the existing media assets and remove any that don't have a corresponding command
		const filteredMediaAssets = mediaAssets.filter(asset => {
			return currentCommandsSlugs.includes(asset.commandSlug);
		});

		// mix into new array
		const newMediaAssetsArray = [...filteredMediaAssets, ...newMediaAssets];

		// make sure the commands are up-to-date even if the slugs diddnt change
		// this is because the commands themselves could have changed
		newMediaAssetsArray.forEach((asset) => {
			const command = commands[asset.commandSlug];
			if (command)
				asset.commandName = command.command;
		});

		// add the new media assets to the existing, remaining ones
		this.settings.mediaAssets.value = newMediaAssetsArray;
	}


	/**
	 * Perform clean up when the toy is destroyed
	 */
	end(){
		super.end();
		electronAPI.clearTick(this.tickFN);
		if(this.stateTimeout)
			window.clearElectronTimeout(this.stateTimeout);
	}


	/**
	 * Initialize the settings for this toy
	 */
	initSettings() {

		// media settings
		this.buildSettingsBlock({

			mediaAssets: shallowRef([]),
			showPatterName: ref(true),
			chatterNameFontSize: ref(25),
			chatterNameColor: ref('#00ABAE'),
			chatterTextColor: ref('#FFFFFF'),
			chatterNameShadow: ref(true),
			widgetBox: shallowRef({
				x: 20,
				y: 20,
				width: 400,
				height: 200
			}),			
		});
	}


	/**
	 * Initialize the commands for this toy
	 */
	buildCommands() {

		// all commands on this toy will be generated by the user,
		// so empty array. NOTE: user generated commands will never be
		// added to this array, get them through the commands ref
		super.buildCommands([]);
	}
	

	/**
	 * Handle when an incoming command is sent to this toy
	 * 
	 * @param {String} commandSlug - the slug of the command
	 * @param {Object} msg - details about the chat message that invoked the command
	 * @param {Object} user - details about the user that invoked the command (could be dummy if not in database yet)
	 * @param {Array<String>} params - the parameters passed to the command
	 * @param {Object} handshake - object like { accept: Function, reject: Function } to accept or reject the command
	 */
	onCommand(commandSlug, msg, user, params, handshake) {

		// queue the media item & accept the command
		this.queueMediaItem(msg, commandSlug);

		// accept the command which updates the database
		handshake.accept();
	}
	

	/**
	 * Queues a media item when command is run
	 * 
	 * @param {Object} msg - the message object that invoked the command
	 * @param {String} shortSlug - the command slug suffix (e.g. "1")
	 */
	queueMediaItem(msg, shortSlug) {

		// reconstruct the full slug (e.g. "media__1")
		const fullSlug = this.static.slugify(shortSlug);

		// get the media item from the settings via slug
		const mediaAssets = this.settings.mediaAssets.value;
		const mediaItem = mediaAssets.find(item => item.commandSlug === fullSlug);

		// GTFO if we don't have this item
		if (!mediaItem) {
			console.error(`Media item not found for slug: ${fullSlug}`);
			return;
		}

		// show on system console
		this.chatToysApp.log.msg(`${msg.author} used media !${mediaItem.commandName}`);

		// repack the media item into a queue item
		const queueItem = {
			author: msg.author,
			commandName: mediaItem.commandName,
			imagePath: mediaItem.hasImage ? this.getAssetPath(mediaItem.imageId) : null,
			soundPath: mediaItem.hasSound ? this.getAssetPath(mediaItem.soundId) : null,
			duration: mediaItem.duration,
			volume: mediaItem.volume !== undefined ? mediaItem.volume : 1,
			scale: mediaItem.scale !== undefined ? mediaItem.scale : 1,
		}
		this.stateTickerQueue.addToQueue(queueItem);
	}


	/**
	 * Pops the next media item from the queue
	 */
	handleStateChange(data) {
		
		// if we got null, return to IDLE
		if(data === null) {
			this.mode.value = 'IDLE';
			this.imagePath.value = null;
			this.soundPath.value = null;
			return;
		}

		// otherwise, set the media item
		const mediaItem = data;
		this.author.value = mediaItem.author;
		this.commandName.value = mediaItem.commandName;
		this.soundPath.value = mediaItem.soundPath;
		this.imagePath.value = mediaItem.imagePath;

		// notify our socket refs for volume and scale
		this.volume.value = mediaItem.volume;
		this.scale.value = mediaItem.scale;

		this.stateTimeout = window.setElectronTimeout(()=>{
			this.mode.value = 'PLAY';
		}, 100);
	}

}
