<!--
	connectionSettings/general.vue
	------------------------------

	The "General Settings" tab is misleadingly named - it's mostly OBS
	WebSocket configuration plus the local widget server. Both topics
	covered here because the actual app tab puts them together.
-->
<script>
export const meta = {
	title: 'General Settings (OBS & Server)',
	tags: ['obs', 'websocket', 'server', 'connection'],
	keywords: ['obs-websocket', 'browser source', 'port', 'demo mode', 'localhost'],
	summary: 'Connecting to OBS WebSocket, the local widget server, and demo mode.',
	order: 3,
};
</script>
<template>

	<HelpSection title="OBS WebSocket connection">
		<p>
			OBS exposes a WebSocket interface that external apps can
			use to control it and read its state. Chat-Toys uses the
			connection for two things: detecting when you go live (for
			Auto Chat), and refreshing browser sources after a
			reconnect.
		</p>
		<p>
			You must enable the WebSocket server on the OBS side first:
		</p>
		<ol>
			<li>In OBS, open <HelpKbd>Tools → WebSocket Server Settings</HelpKbd>.</li>
			<li>Check "Enable WebSocket server".</li>
			<li>Note the server port (default 4455).</li>
			<li>Click "Show Connect Info" and copy the password.</li>
		</ol>
		<p>
			Back in Chat-Toys' General Settings, paste the port and
			password, then toggle "Enable OBS Connection" on. The
			status line above tells you whether the handshake worked.
		</p>
		<HelpWarning>
			The WebSocket password is <strong>not</strong> your OBS
			password or your stream key. It's a separate password
			specific to the WebSocket server, generated by OBS itself.
		</HelpWarning>
	</HelpSection>

	<HelpSection title="Auto-refresh browser sources">
		<p>
			When Chat-Toys reconnects to OBS, browser sources for
			widgets may have loaded earlier (while the local widget
			server wasn't yet running). Toggling "Auto Refresh Browser
			Sources Upon Connect" makes the app tell OBS to refresh
			every Chat-Toys browser source whenever the connection is
			re-established, so the widgets pick up the current state.
		</p>
		<HelpTip>
			This is the single setting most likely to fix "the widget
			worked yesterday but is blank today". Leave it on.
		</HelpTip>
	</HelpSection>

	<HelpSection title="Widget Server settings">
		<p>
			Chat-Toys hosts every widget as a regular web page on a
			local HTTP server. OBS points its browser sources at these
			pages — the server doesn't need to be reachable from the
			internet, it only needs to be reachable from OBS on the
			same machine.
		</p>
		<p>
			The <strong>Test Page URL</strong> exists so you can verify
			the server is up: paste it into a regular browser tab and
			you should see "Chat Toys - Works!". If that page doesn't
			load, no widget will work either.
		</p>
	</HelpSection>

	<HelpSection title="Demo Mode">
		<p>
			Demo Mode forces every widget to render in a fake "always
			showing" state so you can position and size them in OBS
			without having to actually trigger them via chat. The
			prize wheel will be spinning, donation pop-ups will be
			visible, media items will be on screen, etc.
		</p>
		<HelpWarning>
			<strong>Turn demo mode off before you go live.</strong>
			Otherwise viewers will see widgets stuck in a permanently-
			active state.
		</HelpWarning>
	</HelpSection>

	<HelpSection title="Server Port (advanced)">
		<p>
			You almost never need to touch this. The widget server
			picks a port at startup; it has nothing to do with the OBS
			WebSocket port. The only reason to change it is if you
			already have something else running on the picked port.
		</p>
		<p>
			If you do change it, every browser-source URL in OBS needs
			to be updated to match the new port. The recommended
			procedure is: change the number, click "Restart Server",
			then restart the entire Chat-Toys app to make sure
			everything re-binds cleanly.
		</p>
	</HelpSection>

</template>
